### ISSUE TITLE
uk-overlay-icon

### ISSUE THREAD

**Issue by doublex** [uikit/uikit#1419]
Hello,

How can I change the icon of a "uk-overlay-icon"? "uk-overlay-panel uk-overlay-icon uk-icon-camera" -> shows the magnify.

Thanks a lot
Marcus

**Comment by doublex** [comment]
Maybe the fix is to remove 'content: "\f002";' from '.uk-overlay-icon:before'?
Thanks a lot
Marcus

**Comment by malles** [comment]
You can override that selector and set the content to that of the camera icon, "\f030".

**Comment by doublex** [comment]
Yes - but it would be nice if one could overwrite the content by adding a "uk-icon-*" class, e.g.:
&lt;div class=&quot;uk-overlay-panel uk-overlay-icon __uk-icon-camera__&quot;&gt;&lt;/div&gt;

But it does not wok, because the rule ".uk-overlay-icon:before" is stronger than ".uk-icon-*".

Thanks!

**Comment by bbenne10** [comment]
:+1:
This is an extremely silly problem to continue to have. There are at least two other issues that bring this up, and no note in the documentation about this. The first was closed by simply saying "compile again after changing the  variable that controls this", which works but is EXTREMELY inflexible (what if I want different overlays on different types of things with different meanings?). The second answer is "change the class that's generated after the less is compiled", which is also a bad answer since the reason I'm using this framework is to minimize the amount of CSS I'm writing. If I wanted to do this by hand, I would. 

There's no reason that this can't be simply solved by either adding `!important` to all `.uk-icon-*`'s `content` declarations, or (and I think this is a better solution) making it an error case to use `uk-overlay-icon` without also specifying an associated icon by also specifying `uk-icon-*`. This would mean that the `content` declaration could be removed from `uk-overlay-icon` and the controlling variable could be removed (provided it's not used anywhere else). This could be documented and all of us would be happy. 

Would a PR be accepted here? Provided I'm not missing something, I'll be happy to make the required changes and open one.

**Comment by bbenne10** [comment]
After having a look at the code, it does look like fixing this the second way (removing the default icon) is as simple as I thought. I'll go ahead and create a PR.

**Comment by yodiyo** [comment]
Yes, this would be a nice fix, thanks.

**Comment by jgbneatdesign** [comment]
What's up with this issue? Has it been resolved? Is the @bbenne10's PR accepted? It's been more than a year. I like UIkit but it's still not mature enough I think. And issues are not taken care of either. In this case I can't really use it for large projects as I intended to. So sad!

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
