### ISSUE TITLE
CDN auto-update broken

### ISSUE THREAD

**Issue by PeterDaveHello** [uikit/uikit#2678]
Hi there,

I'm Peter from @cdnjs, as requested in #153, @aheinze made a pull request: https://github.com/cdnjs/cdnjs/pull/2189 to host uikit on cdnjs, to make sure the human works minimum, I further enabled auto-update in https://github.com/cdnjs/cdnjs/commit/5a6c3a0dc2c3331a1a114859186f93fa0eaca96a, which will pull new releases via git tags, using `dist/` folder, however, this folder seems to be removed since v2.27.3, which makes auto-update broken on CDNJS, I wonder if is possible to add it back so that we can pull the latest release automatically? Thanks a lot!

Best,
Peter

**Comment by aheinze** [comment]
Hi Peter,

the ```dist/``` is available since UIkit v3 ... the releases for UIkit v.2.x are now in the branch ```v2/dist```. Maybe it is possible to update the auto-update to recognize whether it is 2.x or 3.x?
This would be awesome. If it creates to much circumstances, then please just recognize any UIkit 3 updates.

Thank you for your work and time!

**Comment by PeterDaveHello** [comment]
Hi @aheinze,

Thanks for the updates, as we're using git "tag" to recognize version, branch is kind of different purpose at this point, for `v2/dist`, not like the tags, it'll be a little bit hard to determine which version should be fetched as from branch, so it's better to use tag here, what do you think?

**Comment by florianletsch** [comment]
Hey @PeterDaveHello. Would it be possible to use the npm package for updating instead? That one always includes the `dist` folder, both for UIkit 2.x and 3.x releases.

For example you can review this locally:

```
npm install --save uikit@3.0.0-beta.24 # UIkit 3
npm install --save uikit@2.27.4 # UIkit 2
```

**Comment by PeterDaveHello** [comment]
Looks fine.

**Comment by florianletsch** [comment]
Awesome. Thanks @PeterDaveHello for your work with cdnjs :)

**Comment by janschoenherr** [comment]
Hi Peter,

it seems the latest version of UIkit 3.1.6 isn't available at cdnjs. There should not be any substantial changes in that version compared to UIkit 3.1.5. Can you help with this?

**Comment by PeterDaveHello** [comment]
@janschoenherr should be fixed now, thank you!

**Comment by janschoenherr** [comment]
Hi Peter,

could you please update UIkit at cdnjs?

Thank you

**Comment by PeterDaveHello** [comment]
Looks updated with a short delay, I patched the bot with a hotfix should prevent that in the future.

**Comment by janschoenherr** [comment]
@PeterDaveHello Thanks!

**Comment by janschoenherr** [comment]
@PeterDaveHello I am sorry, but it still does not seem to auto-update.

**Comment by PeterDaveHello** [comment]
Noticed! The reason is the difference of directory/file not totally the same, the bot currently add the new versions which has 100% same structure with the previous version, that's something that we can't automatically handle yet. If you don't mind, ping me every time when it needs to change, I'll make sure it's update to date, sorry for the inconvenience, but we are really short of resource to maintain the project and to enhance features in the same time, as currently I'm the only one maintains the libraries.

**Comment by janschoenherr** [comment]
Thank you very much! I will ping you for the next release. 😀

**Comment by PeterDaveHello** [comment]
BTW, the versions has the same structure as previous should be added automatically without pinging ;)

**Comment by janschoenherr** [comment]
@PeterDaveHello Hi, is there something we could do, to get the autoupdate working again? The folder structure did not change (should not have changed) between minor versions.

**Comment by PeterDaveHello** [comment]
Sorry but I no longer work on cdnjs project, there are some internal issues last for a while, I suggest you contact @MattIPv4 or @ryankirkman, thanks.

**Comment by janschoenherr** [comment]
Thanks @PeterDaveHello I've sent an email to @MattIPv4.

**Comment by MattIPv4** [comment]
👋 You'll want to create a new PR that updates the auto-update config on cdnjs to pull the correct files and also manually add the latest version to cdnjs in the same PR.

**Comment by MattIPv4** [comment]
Frankly though, I have no idea what the future holds for the CDN, we have almost no access currently: https://github.com/cdnjs/cdnjs/issues/13524

**Comment by robertotremonti** [comment]
I confirm cdnjs auto-update is still broken. Now we are 3 updates behind.

**Comment by MattIPv4** [comment]
Cloudflare now have an engineer working on getting cdnjs back up to date and getting the automation for updating working again: https://github.com/cdnjs/cdnjs/issues/13524#issuecomment-548893758

**Comment by janschoenherr** [comment]
@PeterDaveHello Thanks for updating UIkit! It's much appreciated.

**Comment by PeterDaveHello** [comment]
I just help commit it to lower the negative affect may cause, but the CDN deployment is still rely on Cloudflare, seems not working right now.
