### ISSUE TITLE
Module not found: Error: Can't resolve 'uikit-util'

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3399]
### UIkit version
3.0.0-rc.2

### Steps to reproduce

I am trying to follow instructions here in order to include `UIkit` in my project:

https://gitter.im/uikit/uikit?at=5a4f2b5b232e79134dcad1a6

I have done this:  

```
npm install --save-dev uikit
cd node_modules/uikit
npm install
npm run compile
```

I created my own `uikit.js` file.  

My directory structure is:

    |-- dist
    |-- node_modules
        |-- uikit
    |-- src
        |-- js
            |-- my_entry_file.js
            |-- uikit.js

**uikit.js**

```
import UIkit from 'uikit/dist/js/uikit-core';
import Countdown from 'uikit/dist/js/components/countdown';
import Filter from 'uikit/dist/js/components/filter'; // new
import GridParallax from 'uikit/dist/js/components/grid-parallax';
import Lightbox from 'uikit/dist/js/components/lightbox';
import LightboxPanel from 'uikit/dist/js/components/lightbox-panel'; // new
import Notification from 'uikit/dist/js/components/notification';
import Parallax from 'uikit/dist/js/components/parallax';
import Slider from 'uikit/dist/js/components/slider'; // new
import SliderParallax from 'uikit/dist/js/components/slider-parallax'; // new
import Slideshow from 'uikit/dist/js/components/slideshow';
import Sortable from 'uikit/dist/js/components/sortable';
import Tooltip from 'uikit/dist/js/components/tooltip';
import Upload from 'uikit/dist/js/components/upload';

UIkit.use(Countdown);
UIkit.use(Filter); // new
UIkit.use(GridParallax);
UIkit.use(Lightbox);
UIkit.use(LightboxPanel); // new
UIkit.use(Notification);
UIkit.use(Parallax);
UIkit.use(Slider); // new
UIkit.use(SliderParallax); // new
UIkit.use(Slideshow);
UIkit.use(Sortable);
UIkit.use(Tooltip);
UIkit.use(Upload);
```

**webpack.config.js**

```
const path = require('path');
const UglifyJsPlugin = require("uglifyjs-webpack-plugin"); 

var webpack = require("webpack");

module.exports = {
    entry: "./src/js/my_entry_file.js",
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "dist/js")
    },
    mode: "development",
    module: {
        rules: [{
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: ["env", "stage-0"]
                    }
                }
            },
            {
                test: /\.css$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" }
                ]
            },
            {
                test: /\.less$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" },
                    { loader: "less-loader" }
                ]
            },
            {
                test: /\.jpg$/,
                use: [
                    { loader: "url-loader" }
                ]
            }
        ]
    },
    plugins: [
       new UglifyJsPlugin(),
       new webpack.ProvidePlugin({
            $: "./jquery-3.3.1",
            jQuery: "./jquery-3.3.1"
        })
    ]
}
```

### What is Expected?

I expect the `webpack` build to complete in such a way that I have `UIkit` within my project.  

### What is actually happening?

I get these error when running `webpack`:

```
ERROR in ./node_modules/uikit/dist/js/components/upload.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/upload.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/countdown.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/countdown.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/filter.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/filter.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/slider-parallax.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/slider-parallax.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/parallax.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/parallax.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/tooltip.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/tooltip.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/notification.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/notification.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/slider.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/slider.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/sortable.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/sortable.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/lightbox-panel.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/lightbox-panel.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/lightbox.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/lightbox.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

ERROR in ./node_modules/uikit/dist/js/components/slideshow.js
Module not found: Error: Can't resolve 'uikit-util' in 'C:\Users\Me\Documents\my_repo\node_modules\uikit\dist\js\components'
 @ ./node_modules/uikit/dist/js/components/slideshow.js 4:92-113
 @ ./src/js/uikit.js
 @ ./src/js/common.js

```

**Comment by aarongerig** [comment]
You have to set the alias in your webpack config: https://github.com/uikit/uikit/blob/develop/webpack.config.js#L40

Also in order to add components to UIkit use the following syntax: `UIkit.component('filter', Filter);`
The icons still have to be used like `UIkit.use(Icons);`

**Comment by oshihirii** [comment]
I added the following to `weback.config.js` and the error messages went away:

```
resolve: {
alias: {
'uikit-util': path.resolve(__dirname, '/node_modules/uikit/src/js/util')
}
}
```
Re: second instruction:

> Also in order to add components to UIkit use the following syntax: `UIkit.component('filter', Filter);`

Does that mean, change this in `uikit.js`:

```
UIkit.use(Countdown);
UIkit.use(Filter); // new
UIkit.use(GridParallax);
UIkit.use(Lightbox);
UIkit.use(LightboxPanel); // new
UIkit.use(Notification);
UIkit.use(Parallax);
UIkit.use(Slider); // new
UIkit.use(SliderParallax); // new
UIkit.use(Slideshow);
UIkit.use(Sortable);
UIkit.use(Tooltip);
UIkit.use(Upload);
```

to this:

```
UIkit.component('countdown', Countdown);
UIkit.component('filter', Filter); // new
UIkit.component('gridparallax', GridParallax);
UIkit.component('lightbox', Lightbox);
UIkit.component('lightboxpanel', LightboxPanel); // new
UIkit.component('notification', Notification);
UIkit.component('parallax', Parallax);
UIkit.component('slider', Slider); // new
UIkit.component('sliderparallax', SliderParallax); // new
UIkit.component('slideshow', Slideshow);
UIkit.component('sortable', Sortable);
UIkit.component('tooltip', Tooltip);
UIkit.component('upload', Upload);
```

Re: the third statement, I'm not sure what that means, as `Icons` is not mentioned in my `uikit.js` file.  

> The icons still have to be used like `UIkit.use(Icons);`

For reference, unfortunately I don't really understand what any of the above is actually doing, I am just trying to follow the instructions so I can keep using `UIkit` in my project, which I love!  So any detail is appreciated!  

Thanks.

**Comment by aarongerig** [comment]
Almost, you have to import your components like this https://github.com/uikit/uikit/blob/develop/src/js/uikit.js#L16-L28

You could also import the icons in that very same file as showed in the documentation: https://getuikit.com/docs/webpack

With those lines your either activating or deactivating JavaScript components of UIkit. Simply comment out the one's you don't need and you'll get a reduced filesize.

**Comment by aarongerig** [comment]
Yes, now you're on the right track! We have the same problem and the issue has been already been reported and is resolved already as well: https://github.com/uikit/uikit/commit/a4520d1fdd8f3d0595c677371388ef484961630a

As soon as we have a new release this problem will no longer occur. ;)

**Comment by oshihirii** [comment]
Hmm, I looked at that commit and changed the following at line 62 (as was done in the commit):

    const id = hyphenate(id);

to:

    const id = hyphenate(name);

and ran `npm run compile` from `my_repo/node_modules/uikit`, then ran webpack from `my_repo` and now get this error on frontend:

> Uncaught TypeError: Cannot set property 'name' of undefined
>     at Function.UIkit.component (uikit-core.js:3375)
>     at eval (uikit.js:77)
>     at Object../src/js/uikit.js (bundle.js:197)
>     at e (bundle.js:1)
>     at Object.eval (common.js:27)
>     at eval (common.js:1526)
>     at Object../src/js/common.js (bundle.js:169)
>     at e (bundle.js:1)
>     at ./node_modules/process/browser.js (bundle.js:1)
>     at bundle.js:1

**Comment by oshihirii** [comment]
I saw `v3.0.0-rc.3` was [released](https://github.com/uikit/uikit/releases/tag/v3.0.0-rc.3), so I did the following:

    cd Documents/my_repo
    
    npm install --save-dev uikit
    cd node_modules/uikit
    npm install
    npm install yarn
    npm run compile

    cd Documents/my_repo
    
    npm run webpack

The build completes, but I still get this error on the frontend:

> Uncaught TypeError: Cannot set property 'name' of undefined
>     at Function.UIkit.component (uikit-core.js:3375)
>     at eval (uikit.js:77)
>     at Object../src/js/uikit.js (bundle.js:217)
>     at e (bundle.js:1)
>     at Object.eval (my_entry_file.js:29)
>     at eval (my_entry_file.js:1530)
>     at Object../src/js/my_entry_file.js (bundle.js:189)
>     at e (bundle.js:1)
>     at ./node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./src/css/custom_uikit_theme/toolstheme.less (bundle.js:1)
>     at bundle.js:1

**Comment by oshihirii** [comment]
I commented out:

    import GridParallax from 'uikit/dist/js/components/grid-parallax';

and:

    UIkit.component('gridParallax', GridParallax);

from `my_repo/src/js/uikit.js` and that error seems to have gone away.

**Comment by janschoenherr** [comment]
Grid Parallax has been merged into the Grid component and no longer exists standalone.

**Comment by oshihirii** [comment]
PS Yesssss!  I finally have UIkit in my project and a custom `.less` theme external to node_modules (all via webpack )!   Thanks for your help @aarongerig !!

**Comment by razvanioan** [comment]
I am trying myself to build a custom UIkit package for a very small landing page, needing only Slideshow component, using Webpack 4 & Terser minimizer.

I am very confused about the build result file size.

- if I import only `UIkit core` & `Slideshow` component I get **138 KB** in size (slightly bigger than `uikit.min.js` which includes everything, but there's some extra Webpack bootstrap I assume)

```javascript
import UIkit from 'uikit/dist/js/uikit-core'
import Slideshow from 'uikit/dist/js/components/slideshow'
UIkit.component('slideshow', Slideshow)
```

- if I import entire `uikit` (from node_modules) I get the same size of **138 KB**, but I can use all of the components

```javascript
import UIkit from 'uikit'
```

Part from the webpack.config.js

```javascript
module.exports {
  optimization: {
    minimizer: [
      new TerserJSPlugin({
        sourceMap: false,
        parallel: true,
        terserOptions: {
          ecma: 6
        }
      }),

      new OptimizeCSSAssetsPlugin()
    ]
  },

  resolve: {
    alias: {
      'uikit-util': path.resolve(__dirname, 'node_modules/uikit/src/js/util')
    }
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      }
    ]
  }

  // ...
}
```

What am I missing here ?
